name: george_flutter
description: George

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.17
  flutter_google_places: ^0.1.4
  location: ^1.4.1
  google_sign_in: ^3.2.2
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.2+1
  toast: ^0.1.3
  firebase_crashlytics: ^0.0.4
  flutter_fimber: ^0.2.0
  intl: ^0.15.7
  shared_preferences: ^0.4.2
  json_annotation: ^2.0.0
  cached_network_image: ^0.4.0
  url_launcher: ^5.0.3

# flutter packages get
# flutter packages pub run flutter_launcher_icons:main
dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.5.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/ic_launcher.png"
  image_path_android: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
